import os
import smtplib
from email.message import EmailMessage
import yfinance as yf
from datetime import datetime

# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------
SENDER_EMAIL = "anjo28mj@gmail.com"
SENDER_PASSWORD = os.environ.get("EMAIL_APP_PASSWORD")

# List of subscribers (could be moved to a JSON file or DB later)
SUBSCRIBERS = [
    "anjo28mj@gmail.com" # Defaulting to sender as recipient for testing
]

# Tickers to summarize in the daily alert
WATCHLIST = ["^NSEI", "RELIANCE.NS", "TCS.NS", "AAPL", "MSFT"]

def fetch_market_summary():
    """Fetches end-of-day summary for the watchlist."""
    print("Fetching market data...")
    summary_lines = []
    
    for ticker in WATCHLIST:
        try:
            asset = yf.Ticker(ticker)
            data = asset.history(period="2d")
            
            if len(data) >= 2:
                prev_close = data['Close'].iloc[0]
                current_price = data['Close'].iloc[1]
                change = current_price - prev_close
                change_pct = (change / prev_close) * 100
                
                sign = "+" if change >= 0 else ""
                color = "green" if change >= 0 else "red"
                
                line = f"<li><strong>{ticker}</strong>: {current_price:.2f} <span style='color:{color};'>({sign}{change_pct:.2f}%)</span></li>"
                summary_lines.append(line)
            else:
                summary_lines.append(f"<li><strong>{ticker}</strong>: Data unavailable</li>")
        except Exception as e:
            print(f"Failed to fetch {ticker}: {e}")
            summary_lines.append(f"<li><strong>{ticker}</strong>: Error fetching data</li>")
            
    return "".join(summary_lines)

def send_emails(html_content):
    """Sends the HTML email to all subscribers."""
    if not SENDER_PASSWORD:
        print("ERROR: EMAIL_APP_PASSWORD environment variable is not set. Exiting.")
        return
        
    print(f"Sending emails to {len(SUBSCRIBERS)} subscribers...")
    
    try:
        # Connect to Gmail's SMTP server
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        
        for recipient in SUBSCRIBERS:
            msg = EmailMessage()
            msg['Subject'] = f"ALPHA Daily Market Alert - {datetime.now().strftime('%Y-%m-%d')}"
            msg['From'] = SENDER_EMAIL
            msg['To'] = recipient
            
            # Set email body to HTML
            msg.set_content("Please enable HTML to view this email.")
            msg.add_alternative(html_content, subtype='html')
            
            server.send_message(msg)
            print(f"Sent successfully to {recipient}")
            
        server.quit()
        print("All emails dispatched successfully.")
    except Exception as e:
        print(f"Failed to send emails: {e}")

if __name__ == "__main__":
    print("Starting ALPHA Daily Market Alert Job...")
    market_data_html = fetch_market_summary()
    
    email_html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;">
        <div style="background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
          <h2 style="color: #0284C7; border-bottom: 2px solid #f0f0f0; padding-bottom: 10px;">ALPHA // Daily Market Summary</h2>
          <p style="color: #555;">Here is your automated end-of-day market update.</p>
          
          <ul style="list-style-type: none; padding-left: 0; line-height: 1.8;">
            {market_data_html}
          </ul>
          
          <p style="font-size: 12px; color: #999; margin-top: 20px;">
            This is an automated alert generated by the ALPHA Quant-Semantic Terminal Git Automation.<br>
            To unsubscribe, please update the SUBSCRIBERS list in the repository.
          </p>
        </div>
      </body>
    </html>
    """
    
    send_emails(email_html)
